---
- name: Automate SNOW 
  gather_facts: false
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm


  tasks:

    # Always give your tasks a useful name
    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: Ansible Automation Platform
        short_description: "This is a new incident"
        description: "{{ lookup('env', 'SN_USERNAME') }} successfully created a new incident!"
        impact: low
        urgency: low
      register: new_incident

    - debug:
        msg: "{{ new_incident }}"
    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
